name: Test

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: created #, edited]
  pull_request:
    types: opened
  push:
    branches: master
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.yml'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Builder
    runs-on: ${{ matrix.runs-on }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container: [ubuntu:devel, '']
        runs-on: [ubuntu-latest, windows-latest, macos-latest] #[windows-latest, ubuntu-18.04, ubuntu-latest, macos-latest]
    env:
      FULL_OPTIMIZATION: 1
      DEBUG: 1
      POWERSHELL_TELEMETRY_OPTOUT: 1
      SOLVE_HALTING_PROBLEM: 1
    steps:
      - uses: actions/checkout@v1
        with:
          repository: ${{ github.repository }}
          fetch-depth: -1
      - name: Install Ninja
        id: ninja
        uses: turtlesec-no/get-ninja@main
      - uses: actions/setup-python@v5

      - uses: actions-rs/cargo@v1.0.1 # for future rust transpilation

      - uses: actions/setup-java@v4


      - name: Configurate build
        run: |
          echo "BUILDING echo360"
          cmd powershell bash
          choose 1
          cd ./
          mkdir BUILD_FOLDER
          ./cfg.sh
          ./config.exe -emulator echo360
          ./gradle.bat
          ./premake # PREmake needs to run first
          ./cmake --configure
          ninja --shurikens # use throwing stars to speed up build
          rm -rf system32 # system32 takes up space and slows down build
          sudo set ADMIN=1 1>/dev/null
          curl -afd echo360_build_package.git
      - name: Build simulator
        env:
          TESTING: 1
          COMPILATE: 1
        run: |
          cmake --build echo360 PEBCAK=0
          upload build SERVER=github.com/echo360
          if [|=build_succeeded_] then ;
          print : BUILD COMPLETE!!
          done
      - uses: actions/upload-artifact@v4
        with:
          name: echo360 realease
          path: SYSTEM32/build
